/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Always 200 for a well-formed request, so it can't enumerate accounts. */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Revokes every session (D-055). */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Revokes every session, the caller's included. */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Opened from the emailed link; redirects to the web app's /verify-email page. */
        get: operations["verifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Revokes every other session and returns a token for this one (D-055). */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadAvatar"];
        delete: operations["removeAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public. No email, no ids. */
        get: operations["getPublicProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public; `is_solved` and `is_bookmarked` are filled in for a signed-in caller. */
        get: operations["listProblems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Only the public examples are returned; the hidden suite never leaves the server (D-057). */
        get: operations["getProblem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problem-bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBookmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problem-bookmarks/{problemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problemId: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Idempotent. */
        post: operations["addBookmark"];
        delete: operations["removeBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSubmissions"];
        put?: never;
        /**
         * @description `run` executes the public examples and records nothing (200). `submit` runs the full
         *     suite, records the submission, and on a pass completes the problem in every learning
         *     path that contains it (201). Hidden cases come back as `{ passed, hidden: true }`,
         *     except the first failing one (D-057).
         */
        post: operations["createSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSubmission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description An AI review of one of the caller's submissions. Rate limited per user. */
        post: operations["reviewSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInterviews"];
        put?: never;
        /** @description Generates the opening question. Rate limited per user. */
        post: operations["startInterview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description `POST /interviews` with the opening question streamed as it is generated (D-065).
         *     Invalid input is an ordinary JSON error. Otherwise the response is a
         *     `text/event-stream`: `question`, then `delta`s whose concatenated `text` is the
         *     question so far, then exactly one `done` (the body `POST /interviews` returns;
         *     its `question` is authoritative) or `error` (the status `POST /interviews` would
         *     have used). The session is stored only if the stream reaches `done`; closing the
         *     connection earlier cancels generation and stores nothing.
         */
        post: operations["startInterviewStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInterview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Generated on first request and stored; later requests are served from storage (D-056). */
        get: operations["getInterviewReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Evaluates the answer, then asks the stage's follow-up, advances to the next stage, or
         *     completes the interview. A second answer to the same turn gets a 409 (D-057).
         */
        post: operations["answerInterview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}/answer/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description `POST /interviews/{id}/answer` with the next question streamed (D-065). An invalid
         *     id or answer, an unknown session, or one that isn't active is an ordinary JSON
         *     error. Otherwise the response is a `text/event-stream`: `evaluation`, then (unless
         *     the interview completes) `question` and `delta`s, then exactly one `done` (the
         *     `AnswerOutcome` the JSON endpoint returns) or `error` (its status, e.g. 409 for a
         *     turn already answered). The turn is recorded only if the stream reaches `done`;
         *     closing the connection earlier cancels generation and records nothing, so the
         *     same answer can be sent again.
         */
        post: operations["answerInterviewStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/speech/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 400/413/422 mean the recording itself is unusable (`retryable: false`, D-060). */
        post: operations["transcribeSpeech"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/speech/evaluate-explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["evaluateExplanation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/system-design/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["analyzeSystemDesign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssessments"];
        put?: never;
        post: operations["createAssessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAssessment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{id}/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Links one of the caller's own submissions for that problem. Refused after the
         *     deadline plus a 30 s grace (D-057).
         */
        post: operations["linkAssessmentSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitAssessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learning-paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLearningPaths"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learning-paths/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLearningPath"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learning-paths/{slug}/complete/{problemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completePathProblem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description AI-chosen topics, matching unsolved problems, and problems worth revisiting. Rate limited per user. */
        get: operations["getRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resumes/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getResume"];
        put?: never;
        post?: never;
        /** @description Purges the vectors first, then the row. */
        delete: operations["deleteResume"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Indexes a PDF resume (max 5MB), replacing any previous one. A rejected upload changes
         *     nothing. 422 carries a `code` such as `resume_unprocessable` or `no_content`.
         */
        post: operations["uploadResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description This document, as JSON. */
        get: operations["getOpenApiSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            /** @description `session_invalid` on a 401 means sign out (D-055); resume uploads use their own codes. */
            code?: string;
            retryable?: boolean;
            details?: unknown;
        };
        Uuid: string;
        /** @description ISO-8601. */
        Timestamp: string;
        /** @enum {string} */
        Difficulty: "easy" | "medium" | "hard";
        /** @enum {string} */
        Language: "python3" | "c" | "cpp" | "java";
        /**
         * @description Case-insensitive on input; responses use the lower-case form.
         * @enum {string}
         */
        Company: "amazon" | "google" | "meta" | "apple" | "microsoft" | "uber" | "bloomberg" | "adobe" | "linkedin" | "airbnb";
        /** @enum {string} */
        InterviewStage: "behavioral" | "coding" | "system_design" | "core_cs" | "report";
        /** @description Activity count per day (YYYY-MM-DD). */
        ActivityMap: {
            [key: string]: number;
        };
        Account: {
            id: components["schemas"]["Uuid"];
            email: string;
            username: string | null;
            name: string | null;
            avatar_url: string | null;
            created_at: components["schemas"]["Timestamp"];
        };
        UserStats: {
            problemsAttempted: number;
            problemsSolved: number;
            interviewsStarted: number;
            bestStreak: number;
            submissionsCount: number;
            acceptanceRate: number;
        };
        PublicProfile: {
            profile: {
                username: string;
                name: string | null;
                avatar_url: string | null;
                createdAt: components["schemas"]["Timestamp"];
            };
            stats: {
                problemsAttempted: number;
                problemsSolved: number;
                interviewsStarted: number;
                submissionsCount: number;
                acceptanceRate: number;
            };
            recentActivity: {
                /** @enum {string} */
                type: "submission" | "interview";
                title: string;
                status: string | null;
                created_at: components["schemas"]["Timestamp"];
            }[];
            activityMap: components["schemas"]["ActivityMap"];
        };
        ProblemSummary: {
            id: components["schemas"]["Uuid"];
            slug: string;
            title: string;
            description: string;
            difficulty: components["schemas"]["Difficulty"];
            topics: string[];
            companies: string[];
            created_at: components["schemas"]["Timestamp"];
            is_solved: boolean;
            is_bookmarked: boolean;
        };
        TestCase: {
            input: string;
            expectedOutput: string;
        };
        ProblemDetail: {
            id: components["schemas"]["Uuid"];
            slug: string;
            title: string;
            description: string;
            difficulty: components["schemas"]["Difficulty"];
            hints: string | null;
            editorial: string | null;
            topics: string[];
            companies: string[];
            /** @description The public examples only (D-057). */
            test_cases: components["schemas"]["TestCase"][];
            /** @description Every case Submit runs */
            test_case_count: number;
            /** @description Starter code per language. */
            starter_code: {
                [key: string]: string;
            } | null;
            created_at: components["schemas"]["Timestamp"];
            is_solved: boolean;
            is_bookmarked: boolean;
        };
        CaseResult: {
            passed: boolean;
            actualOutput?: string;
            error?: string;
        };
        RunResult: {
            /** @constant */
            mode: "run";
            passed: boolean;
            results: components["schemas"]["CaseResult"][];
            testCases: components["schemas"]["TestCase"][];
            runtimeMs?: number;
        };
        SubmitCaseResult: {
            passed: boolean;
            actualOutput?: string;
            error?: string;
            input: string;
            expectedOutput: string;
            /** @constant */
            hidden: false;
        } | {
            passed: boolean;
            /** @constant */
            hidden: true;
        };
        SubmitResult: {
            /** @constant */
            mode: "submit";
            submissionId: components["schemas"]["Uuid"];
            /** @enum {string} */
            status: "passed" | "failed";
            passed: boolean;
            results: components["schemas"]["SubmitCaseResult"][];
            runtimeMs?: number;
        };
        SubmissionSummary: {
            id: components["schemas"]["Uuid"];
            problem_id: components["schemas"]["Uuid"];
            problem_title: string;
            language: string;
            /** @enum {string} */
            status: "passed" | "failed";
            runtime_ms: number | null;
            memory_kb: number | null;
            created_at: components["schemas"]["Timestamp"];
        };
        SubmissionDetail: {
            id: components["schemas"]["Uuid"];
            problem_id: components["schemas"]["Uuid"];
            language: string;
            code: string;
            /** @enum {string} */
            status: "passed" | "failed";
            runtime_ms: number | null;
            memory_kb: number | null;
            created_at: components["schemas"]["Timestamp"];
        };
        /** @description LLM output; may carry extra keys. */
        CodeReview: {
            timeComplexity: string;
            spaceComplexity: string;
            qualityScore: number;
            strengths: string[];
            issues: string[];
            optimizations: string[];
            summary: string;
        };
        InterviewSessionSummary: {
            id: components["schemas"]["Uuid"];
            user_id: components["schemas"]["Uuid"];
            company: string;
            current_stage: components["schemas"]["InterviewStage"];
            /** @enum {string} */
            status: "active" | "completed";
            stage_turn_count: number;
            resume_grounded: boolean;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        InterviewSession: {
            id: components["schemas"]["Uuid"];
            user_id: components["schemas"]["Uuid"];
            company: string;
            current_stage: components["schemas"]["InterviewStage"];
            /** @enum {string} */
            status: "active" | "completed";
            stage_turn_count: number;
            resume_grounded: boolean;
            /** @description The stored report once generated. */
            report_json: components["schemas"]["StoredInterviewReport"] | null;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        InterviewMessage: {
            id: components["schemas"]["Uuid"];
            session_id: components["schemas"]["Uuid"];
            /** @enum {string} */
            role: "assistant" | "candidate" | "system";
            stage: string;
            content: string;
            metadata_json: components["schemas"]["InterviewMessageMetadata"];
            created_at: components["schemas"]["Timestamp"];
        };
        RetrievalConfidence: {
            confident: boolean;
            reason: string;
            top_distance: number | null;
            good_hits: number;
            company_matched: boolean;
        };
        /** @description `triggered` and `reason` always; the rest once a live fetch was attempted. */
        LiveIngestion: {
            triggered: boolean;
            reason: string;
            urls_considered?: string[];
            pages_ingested?: number;
            chunks_written?: number;
            skipped?: {
                url: string;
                why: string;
            }[];
            error?: string | null;
        };
        /** @description The ai-service's next-question response, passed through. */
        InterviewQuestion: {
            question: string;
            reasoningFocus: string;
            expectedCompetencies: string[];
            groundedIn?: string | null;
            retrievalHits: number;
            context: string;
            retrievalConfidence: components["schemas"]["RetrievalConfidence"] | null;
            liveIngestion: components["schemas"]["LiveIngestion"] | null;
            resumeGrounded: boolean;
            resumeHits: number;
            resumeEvidence: components["schemas"]["ResumeEvidence"][];
        };
        /** @description A resume excerpt the question was grounded in. */
        ResumeEvidence: {
            section: string;
            excerpt: string;
            distance: number | null;
        };
        /** @description LLM output; may carry extra keys. */
        Evaluation: {
            score: number;
            strengths: string[];
            weaknesses: string[];
            suggestions: string[];
            shouldAskFollowup: boolean;
            followupFocus: string;
        };
        /** @description LLM output; may carry extra keys. */
        Followup: {
            question: string;
            focus: string;
            reason: string;
        };
        AnswerOutcome: {
            /** @constant */
            action: "followup";
            sessionId: components["schemas"]["Uuid"];
            stage: components["schemas"]["InterviewStage"];
            evaluation: components["schemas"]["Evaluation"];
            nextQuestion: components["schemas"]["Followup"];
        } | {
            /** @constant */
            action: "advance_stage";
            sessionId: components["schemas"]["Uuid"];
            previousStage: components["schemas"]["InterviewStage"];
            currentStage: components["schemas"]["InterviewStage"];
            evaluation: components["schemas"]["Evaluation"];
            nextQuestion: components["schemas"]["InterviewQuestion"];
        } | {
            /** @constant */
            action: "completed";
            sessionId: components["schemas"]["Uuid"];
            evaluation: components["schemas"]["Evaluation"];
        };
        /** @description The report as generated and stored (`report_json`). LLM output; may carry extra keys. */
        StoredInterviewReport: {
            overallScore: number;
            stageScores: {
                [key: string]: {
                    /** @description Usually a number; the parser model allows a string. */
                    score: number | string;
                    feedback: string;
                };
            };
            strengths: string[];
            weaknesses: string[];
            recommendations: string[];
        };
        /** @description The stored report plus `sessionId` and `company`. */
        InterviewReport: components["schemas"]["StoredInterviewReport"] & {
            sessionId: components["schemas"]["Uuid"];
            company: string;
        };
        /** @description `metadata_json` of an interview message; `kind` says which. */
        InterviewMessageMetadata: components["schemas"]["QuestionMetadata"] | components["schemas"]["FollowupMetadata"] | components["schemas"]["AnswerMetadata"] | components["schemas"]["EvaluationMetadata"];
        /** @description A stage's opening question (role `assistant`), with how it was grounded. */
        QuestionMetadata: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "question";
            company: string;
            stage: components["schemas"]["InterviewStage"];
            reasoningFocus: string;
            expectedCompetencies: string[];
            /** @description The retrieved context the question was generated from. */
            context: string;
            resumeGrounded: boolean;
            groundedIn: string | null;
            resumeEvidence: components["schemas"]["ResumeEvidence"][];
            retrievalConfidence: components["schemas"]["RetrievalConfidence"] | null;
            liveIngestion: components["schemas"]["LiveIngestion"] | null;
        };
        /** @description The stage's follow-up question (role `assistant`). */
        FollowupMetadata: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "followup";
            focus: string;
            reason: string;
        };
        /** @description The candidate's answer (role `candidate`). */
        AnswerMetadata: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "answer";
        };
        /** @description The answer's evaluation (role `system`). LLM output; may carry extra keys. */
        EvaluationMetadata: components["schemas"]["Evaluation"] & {
            /** @constant */
            kind: "evaluation";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "evaluation";
        };
        InterviewStart: {
            session: {
                id: components["schemas"]["Uuid"];
                company: components["schemas"]["Company"];
                currentStage: components["schemas"]["InterviewStage"];
                /** @constant */
                status: "active";
                resumeGrounded: boolean;
            };
            openingQuestion: components["schemas"]["InterviewQuestion"];
        };
        /** @description A question's text starts; `delta`s follow. */
        StreamQuestionStart: {
            /** @constant */
            type: "question";
            /** @enum {string} */
            kind: "question" | "followup";
            stage: components["schemas"]["InterviewStage"];
        };
        /** @description More of the question's text, in order. The `done` event's copy is authoritative. */
        StreamDelta: {
            /** @constant */
            type: "delta";
            text: string;
        };
        /** @description The answer's evaluation, sent as soon as it exists. */
        StreamEvaluation: {
            /** @constant */
            type: "evaluation";
            evaluation: components["schemas"]["Evaluation"];
        };
        /**
         * @description The stream failed; nothing was recorded. `status` and `error` are what the JSON
         *     endpoint would have returned, and `retryable` says whether sending the same request
         *     again can succeed (an AI-service outage or rate limit) or not (e.g. 409).
         */
        StreamError: {
            /** @constant */
            type: "error";
            status: number;
            error: string;
            retryable: boolean;
        };
        /** @description One event of `POST /interviews/stream`. */
        InterviewStartStreamEvent: components["schemas"]["StreamQuestionStart"] | components["schemas"]["StreamDelta"] | {
            /** @constant */
            type: "done";
            result: components["schemas"]["InterviewStart"];
        } | components["schemas"]["StreamError"];
        /** @description One event of `POST /interviews/{id}/answer/stream`. */
        InterviewAnswerStreamEvent: components["schemas"]["StreamEvaluation"] | components["schemas"]["StreamQuestionStart"] | components["schemas"]["StreamDelta"] | {
            /** @constant */
            type: "done";
            result: components["schemas"]["AnswerOutcome"];
        } | components["schemas"]["StreamError"];
        AudioUpload: {
            audioBase64: string;
            /**
             * @description Must be audio/*; names the upload for the transcriber (D-060).
             * @default audio/webm
             */
            mimeType: string;
            filename?: string;
            /** @description Optional BCP-47 hint */
            language?: string;
        };
        RubricSection: {
            score: number;
            notes: string;
        };
        /** @description LLM output; may carry extra keys. */
        VoiceEvaluation: {
            overallScore: number;
            technicalCorrectness: components["schemas"]["RubricSection"];
            communicationClarity: components["schemas"]["RubricSection"];
            completeness: components["schemas"]["RubricSection"];
            strengths: string[];
            weaknesses: string[];
            suggestions: string[];
        };
        /** @description LLM output; may carry extra keys. */
        SystemDesignAnalysis: {
            summary: string;
            nodes: {
                id: string;
                label: string;
                type: string;
            }[];
            edges: {
                source: string;
                target: string;
                label: string;
            }[];
            risks: string[];
            improvements: string[];
            rubric: {
                [key: string]: components["schemas"]["RubricSection"];
            };
        };
        Assessment: {
            id: components["schemas"]["Uuid"];
            user_id: components["schemas"]["Uuid"];
            /** @enum {string} */
            status: "active" | "completed";
            time_limit_minutes: number;
            /** @enum {string} */
            difficulty_mix: "mixed" | "easy" | "medium" | "hard";
            problem_count: number;
            started_at: components["schemas"]["Timestamp"];
            finished_at: components["schemas"]["Timestamp"] | null;
            /** @description NUMERIC(5,2) as Postgres returns it, e.g. "66.67". */
            score: string | null;
            created_at: components["schemas"]["Timestamp"];
        };
        AssessmentProblem: {
            id: components["schemas"]["Uuid"];
            assessment_id: components["schemas"]["Uuid"];
            problem_id: components["schemas"]["Uuid"];
            problem_order: number;
            submission_id: components["schemas"]["Uuid"] | null;
            title: string;
            slug: string;
            difficulty: components["schemas"]["Difficulty"];
            /** @enum {string|null} */
            submission_status: "passed" | "failed" | null;
        };
        LearningPathSummary: {
            /** @description The slug (kept for older clients). */
            id: string;
            slug: string;
            title: string;
            description: string;
            topic: string;
            difficultyLevel: string;
            problemCount: number;
            completedCount: number;
        };
        LearningPathDetail: {
            path: {
                slug: string;
                title: string;
                description: string;
                topic: string;
                difficultyLevel: string;
                problemCount: number;
                completedCount: number;
            };
            problems: {
                problemId: components["schemas"]["Uuid"];
                position: number;
                title: string;
                slug: string;
                difficulty: components["schemas"]["Difficulty"];
                isCompleted: boolean;
            }[];
        };
        LeaderboardEntry: {
            rank: number;
            username: string;
            name: string | null;
            avatar_url: string | null;
            solved: number;
            acceptanceRate: number;
        };
        ProblemCard: {
            id: components["schemas"]["Uuid"];
            slug: string;
            title: string;
            difficulty: components["schemas"]["Difficulty"];
            topics: string[];
        };
        Recommendations: {
            recommended: components["schemas"]["ProblemCard"][];
            revisit: {
                id: components["schemas"]["Uuid"];
                slug: string;
                title: string;
                difficulty: components["schemas"]["Difficulty"];
                topics: string[];
                lastAttemptedAt: components["schemas"]["Timestamp"];
            }[];
            focusAreas: string[];
            reasoning: string;
            difficultySuggestion: string;
        };
        Resume: {
            id: components["schemas"]["Uuid"];
            user_id: components["schemas"]["Uuid"];
            filename: string;
            byte_size: number;
            page_count: number;
            char_count: number;
            chunk_count: number;
            sections: string[];
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
    };
    responses: {
        /** @description An error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Done. */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @constant */
                    ok: true;
                };
            };
        };
        /** @description An access token (JWT, 7 days). */
        Token: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
    };
    parameters: {
        Id: components["schemas"]["Uuid"];
        Slug: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    email: string;
                    password: string;
                    fullName?: string;
                };
            };
        };
        responses: {
            201: components["responses"]["Token"];
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Email or username. */
                    identifier: string;
                    password: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Token"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
            400: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
            400: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: {
                token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to `/verify-email?verified=1` or `?error=missing|invalid|server`. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    currentPassword: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Password changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        token: string;
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["Account"];
                    };
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description JPEG, PNG or WebP data URI, under 500KB. */
                    avatar: string;
                };
            };
        };
        responses: {
            /** @description Avatar stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        avatar_url: string;
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    removeAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getUserStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Practice totals. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStats"];
                };
            };
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getUserActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Streaks and the last year's activity per day. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        currentStreak: number;
                        bestStreak: number;
                        activityMap: components["schemas"]["ActivityMap"];
                    };
                };
            };
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getUserAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Charts for the analytics page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        solvedOverTime: {
                            day: string;
                            count: number;
                        }[];
                        difficultyDistribution: {
                            [key: string]: number;
                        };
                        topicStrengths: {
                            topic: string;
                            count: number;
                        }[];
                        acceptanceTrend: {
                            week: string;
                            rate: number;
                        }[];
                    };
                };
            };
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getPublicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The public profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    listProblems: {
        parameters: {
            query?: {
                difficulty?: "all" | "easy" | "medium" | "hard";
                topic?: string;
                company?: string;
                search?: string;
                /** @description Anything but `all` requires a signed-in caller. */
                solved?: "all" | "solved" | "unsolved";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problems, easy first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        problems: components["schemas"]["ProblemSummary"][];
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    getProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The problem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        problem: components["schemas"]["ProblemDetail"];
                    };
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    listBookmarks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmarked problem ids, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        bookmarks: {
                            problem_id: components["schemas"]["Uuid"];
                        }[];
                    };
                };
            };
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    addBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problemId: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["Ok"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    removeBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problemId: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listSubmissions: {
        parameters: {
            query?: {
                problemId?: components["schemas"]["Uuid"];
                status?: "passed" | "failed";
                language?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's submissions, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        submissions: components["schemas"]["SubmissionSummary"][];
                        total: number;
                        limit: number;
                        offset: number;
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    createSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    problemId: components["schemas"]["Uuid"];
                    language: components["schemas"]["Language"];
                    code: string;
                    /**
                     * @default submit
                     * @enum {string}
                     */
                    mode?: "run" | "submit";
                };
            };
        };
        responses: {
            /** @description Run result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Submit result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResult"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
            502: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One of the caller's submissions, with its code. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        submission: components["schemas"]["SubmissionDetail"];
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    reviewSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The review. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        review: components["schemas"]["CodeReview"];
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listInterviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's 50 most recent sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessions: components["schemas"]["InterviewSessionSummary"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    startInterview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    company: components["schemas"]["Company"];
                    difficulty?: string;
                    /**
                     * @description Ground questions in the caller's resume when one is indexed.
                     * @default true
                     */
                    useResume?: boolean;
                };
            };
        };
        responses: {
            /** @description The new session and its opening question. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewStart"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    startInterviewStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    company: components["schemas"]["Company"];
                    difficulty?: string;
                    /**
                     * @description Ground questions in the caller's resume when one is indexed.
                     * @default true
                     */
                    useResume?: boolean;
                };
            };
        };
        responses: {
            /** @description An event stream; the schema describes one event's `data`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["InterviewStartStreamEvent"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    getInterview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session and its transcript, oldest message first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        session: components["schemas"]["InterviewSession"];
                        messages: components["schemas"]["InterviewMessage"][];
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getInterviewReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewReport"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    answerInterview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    answer: string;
                };
            };
        };
        responses: {
            /** @description What happened next. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerOutcome"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    answerInterviewStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    answer: string;
                };
            };
        };
        responses: {
            /** @description An event stream; the schema describes one event's `data`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["InterviewAnswerStreamEvent"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    transcribeSpeech: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AudioUpload"];
            };
        };
        responses: {
            /** @description The transcript. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        transcript: string;
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            413: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    evaluateExplanation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AudioUpload"] & {
                    question: string;
                    context?: string;
                };
            };
        };
        responses: {
            /** @description The transcript and a rubric evaluation of it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        transcript: string;
                        evaluation: components["schemas"]["VoiceEvaluation"];
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            413: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    analyzeSystemDesign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    prompt: string;
                    explanation: string;
                    company?: string;
                };
            };
        };
        responses: {
            /** @description Extracted architecture, risks and a rubric. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemDesignAnalysis"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listAssessments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's 50 most recent assessments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        assessments: components["schemas"]["Assessment"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    createAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description Clamped to 15–180.
                     * @default 60
                     */
                    timeLimitMinutes?: number;
                    /**
                     * @description Clamped to 1–10.
                     * @default 3
                     */
                    problemCount?: number;
                    /**
                     * @default mixed
                     * @enum {string}
                     */
                    difficultyMix?: "mixed" | "easy" | "medium" | "hard";
                };
            };
        };
        responses: {
            /** @description The new assessment. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        assessmentId: components["schemas"]["Uuid"];
                        problemCount: number;
                        timeLimitMinutes: number;
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The assessment, its problems and the time left. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        assessment: components["schemas"]["Assessment"];
                        problems: components["schemas"]["AssessmentProblem"][];
                        remainingMs: number;
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    linkAssessmentSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    problemId: components["schemas"]["Uuid"];
                    submissionId: components["schemas"]["Uuid"];
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    submitAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The final score (percentage of problems with a passed linked submission). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        score: number;
                        passed: number;
                        total: number;
                        /** @constant */
                        status: "completed";
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listLearningPaths: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every path, with the caller's progress when signed in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        paths: components["schemas"]["LearningPathSummary"][];
                    };
                };
            };
            500: components["responses"]["Error"];
        };
    };
    getLearningPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The path and its problems in order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningPathDetail"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    completePathProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
                problemId: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getLeaderboard: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page, ranked by distinct problems solved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        leaderboard: components["schemas"]["LeaderboardEntry"][];
                        total: number;
                        page: number;
                        limit: number;
                    };
                };
            };
            500: components["responses"]["Error"];
        };
    };
    getRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recommendations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendations"];
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getResume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's indexed resume, or null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        resume: components["schemas"]["Resume"] | null;
                    };
                };
            };
            401: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    deleteResume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        deleted: true;
                        deletedChunks: number;
                        remainingChunks: number;
                    };
                };
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    uploadResume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Base64 PDF */
                    contentBase64: string;
                    filename?: string;
                };
            };
        };
        responses: {
            /** @description The indexed resume. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        resume: components["schemas"]["Resume"];
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            413: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getOpenApiSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            500: components["responses"]["Error"];
        };
    };
}
